---
title: "Final visualization notes"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(tidyverse)
library(survival)
library(survminer)
source("../utils.R")

colors <- c("#800000", "#7d7d7d", "#4d4d4d", "#e9aa03", "#b36955", "#01293a")
```

Load data:
```{r}
df <- read_csv("../data/agg_survival.csv")
surv_df <- prepare_data(df, cox = TRUE)
```

## Visualization 1: Plotting model coefficients

```{r}
# Load logistic regression:
model <- readRDS("../one_year_predictions/models/regressions/stat_logistic.rds")
```

```{r}
model_summary <- summary(model)
coefs <- as.data.frame(model_summary$coefficients)
coefs$var_name <- rownames(coefs)
rownames(coefs) <- NULL

filter(coefs,
       var_name != "number_of_direct_reports_norm",
       var_name != "(Intercept)") %>%
  ggplot(aes(x = Estimate, y = var_name)) +
  geom_point() +
  geom_errorbarh(aes(xmin = Estimate - 1.96 * `Std. Error`,
                     xmax = Estimate + 1.96 * `Std. Error`,
                     color = "#800000")) +
  scale_x_continuous(limits = c(-8, 8), n.breaks = 17) +
  geom_vline(xintercept = 0) +
  labs(x = "Coefficient", y = "Variable") +
  univ_plot_theme +
  theme(legend.position = "none")
```

## Visualization 2: Survival curves

```{r}
make_surv_curve <- function(df, feature, categories) {
  # Makes a survival curve based on a categorical feature
  # Filter data frame:
  df_to_show <- df[df[[feature]] %in% categories, ]
  # Add ns to category labels:
  for (cat in categories) {
    num_cat <- sum(df_to_show[[feature]] == cat)
    lab_ <- str_c(cat, " (n = ", num_cat, ")")
    df_to_show[[feature]] <- recode(df_to_show[[feature]], 
                                    !!!setNames(as.list(lab_), cat))
  }
  formula <- as.formula(paste("Surv(num_years, vol_attrition) ~", feature))
  fit <- survfit(formula = formula, data = df_to_show)
  fit$call$formula <- formula
  if (length(categories) > 1) {
    names(fit$strata) <- gsub(paste0(feature, "="), "", names(fit$strata))
  }
  # Create the plot:
  plot <- ggsurvplot(fit,
                     data = df_to_show,
                     pval = FALSE,
                     conf.int = TRUE,
                     risk.table.col = "strata",
                     linetype = "strata",
                     ggtheme = univ_plot_theme,
                     palette = colors,
                     legend.title = "") +
    labs(x = "Time (years)",
         y = "Retention probability")
  return(plot$plot)
}
```

Number of direct reports:
```{r}
# Create variable:
surv_df$dir_reports_binned <- ifelse(surv_df$number_of_direct_reports > 0,
                                     "> 0",
                                     "0")
plot <- make_surv_curve(surv_df,
                "dir_reports_binned",
                c("> 0", "0")) +
  labs(title = "Number of direct reports")
# Save plot:
# ggsave("plots/direct_reports_surv.pdf", plot)
plot
```

Tenure:
```{r}
surv_df$tenure_binned <- ifelse(surv_df$tenure > 8,
                                "> 8 years",
                                "<= 8 years")
plot <- make_surv_curve(surv_df, "tenure_binned", c("> 8 years",
                                            "<= 8 years")) +
  labs(title = "Tenure")
# ggsave("plots/tenure_surv.pdf", plot)
plot
```

Reporting hierarchy level:
```{r}
surv_df$rhl_binned <- ifelse(surv_df$reporting_hierarchy_level >= 8,
                             ">= 8",
                             "< 8")
plot <- make_surv_curve(surv_df, "rhl_binned", c(">= 8", "< 8")) +
  labs(title = "Reporting hierarchy level")
ggsave("plots/reporting_hierarchy_surv.pdf", plot)
```

Management level:
```{r}
surv_df$ml_binned <- ifelse(surv_df$management_level_encoded < 2,
                             "Associate",
                             "Other")
plot <- make_surv_curve(surv_df, "ml_binned", c("Associate", "Other")) +
  labs(title = "Management level")
ggsave("plots/management_level_surv.pdf", plot)
# plot
```

Position in range (Local grade grouping filtered out):
```{r}
surv_df$por_binned <- ifelse(surv_df$position_in_range >= 0.6,
                             ">= 0.6",
                             "< 0.6")
plot <- make_surv_curve(filter(surv_df, grade_grouping_encoded != 4),
                "por_binned",
                c(">= 0.6", "< 0.6")) +
  labs(title = "Position in range",
       caption = "Non-local grade grouping")
ggsave("plots/pos_in_range_surv.pdf", plot)
```



