---
title: "One-Year Predictions: Decision Tree"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

Import libraries:
```{r}
library(tidyverse)
library(caret)
library(rpart.plot)
library(ROCR)
library(randomForest)
library(here)
source("../utils.R")
set.seed(15)
```
Load data:
```{r}
df <- read_csv(here("data", "agg_one_year.csv"))
```

Data cleaning:
```{r}
data <- prepare_data_for_DT(df, exclude_cols = c("cost_centre", "company",
                                                 "elt", "continent",
                                                 "number_of_direct_reports",
                                                 "potential", "annual_review",
                                                 "management_level"))
```

Split data into train, validation, and test sets:
```{r}
split <- split_data(data)
train_data <- split[[1]]
validate_data <- split[[2]]
test_data <- split[[3]]
# Combine train data and validate data together (no need for 3 groups):
train_data <- rbind(train_data, validate_data)

# Implement class weights to account for biased dataset:
class_weights <- ifelse(train_data$vol_attrition_next_year == "0",
                        1,
                        sum(train_data$vol_attrition_next_year == 0) /
                          sum(train_data$vol_attrition_next_year == 1))
```


**Train decision tree classifier using cross-validation:**

Cross-validated model:
```{r}
# Define repeated sampling settings:
nfolds <- 10
ctrl <- trainControl(method = "cv",
                     number = nfolds)
# Train model (might take a while depending on settings):
model <- train(
  vol_attrition_next_year ~ .,
  data = train_data,
  method = "rpart",
  trControl = ctrl,
  weights = class_weights
)
# Save the model:
saveRDS(model, file = "models/decision_trees/cv_model_v2.rds")
# Load the model if it's already trained:
model <- readRDS(here("one_year_predictions", "models", "decision_trees", "cv_model_v2.rds"))
print(model)
```

Evaluate model on validation set:
```{r}
# Generate predictions from model:
y_probs <- predict(model, newdata = test_data, type = "prob")[, "1"]
evaluate_class_model(y_probs, test_data$vol_attrition_next_year,
                     file_path = here("data_visualization", "plots", "dt_v2_roc.pdf"))
```

Display the model:
```{r}
rpart_model <- model$finalModel
# Save the plot:
pdf(here("one_year_predictions", "models", "deicision_trees",
         "cv_model_v2.pdf"))
rpart.plot(rpart_model)
dev.off()
```

Look at significant variables:
```{r}
rpart_model <- model$finalModel
rpart_model$variable.importance[1:20]
```